[package]
name = "server"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio.workspace = true
axum = { version = "0.7.5", features = ["macros"] }
axum-server = "0.6.0"
serde = { version = "1.0.204", features = ["derive"] }
envy = "0.4.2"
serde_json = "1.0.120"
tracing = "0.1.40"
tracing-subscriber = "0.3.18"
async-trait = "0.1.81"
